SHELL := /usr/bin/env bash

.PHONY: next-app
next-app:
	pushd next-app && docker-compose up && popd

.PHONY: next-app-jwt
next-app:
	pushd next-app-jwt && docker-compose up && popd

.PHONY: next-app-openid
next-app:
	pushd next-app-openid && docker-compose up && popd
